//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_Client_KK.FunctionsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FunctionsReference.IFunction")]
    public interface IFunction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/IsPrimeNumber", ReplyAction="http://tempuri.org/IFunction/IsPrimeNumberResponse")]
        string IsPrimeNumber(string inputStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/IsPrimeNumber", ReplyAction="http://tempuri.org/IFunction/IsPrimeNumberResponse")]
        System.Threading.Tasks.Task<string> IsPrimeNumberAsync(string inputStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/SumOfDigits", ReplyAction="http://tempuri.org/IFunction/SumOfDigitsResponse")]
        string SumOfDigits(string inputStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/SumOfDigits", ReplyAction="http://tempuri.org/IFunction/SumOfDigitsResponse")]
        System.Threading.Tasks.Task<string> SumOfDigitsAsync(string inputStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/ReverseAString", ReplyAction="http://tempuri.org/IFunction/ReverseAStringResponse")]
        string ReverseAString(string inputStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/ReverseAString", ReplyAction="http://tempuri.org/IFunction/ReverseAStringResponse")]
        System.Threading.Tasks.Task<string> ReverseAStringAsync(string inputStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/PrintHtml", ReplyAction="http://tempuri.org/IFunction/PrintHtmlResponse")]
        string PrintHtml(string inputStr1, string inputStr2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/PrintHtml", ReplyAction="http://tempuri.org/IFunction/PrintHtmlResponse")]
        System.Threading.Tasks.Task<string> PrintHtmlAsync(string inputStr1, string inputStr2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/SortNumbers", ReplyAction="http://tempuri.org/IFunction/SortNumbersResponse")]
        string SortNumbers(int sortType, int[] inputArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunction/SortNumbers", ReplyAction="http://tempuri.org/IFunction/SortNumbersResponse")]
        System.Threading.Tasks.Task<string> SortNumbersAsync(int sortType, int[] inputArray);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFunctionChannel : Assignment1_Client_KK.FunctionsReference.IFunction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FunctionClient : System.ServiceModel.ClientBase<Assignment1_Client_KK.FunctionsReference.IFunction>, Assignment1_Client_KK.FunctionsReference.IFunction {
        
        public FunctionClient() {
        }
        
        public FunctionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FunctionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string IsPrimeNumber(string inputStr) {
            return base.Channel.IsPrimeNumber(inputStr);
        }
        
        public System.Threading.Tasks.Task<string> IsPrimeNumberAsync(string inputStr) {
            return base.Channel.IsPrimeNumberAsync(inputStr);
        }
        
        public string SumOfDigits(string inputStr) {
            return base.Channel.SumOfDigits(inputStr);
        }
        
        public System.Threading.Tasks.Task<string> SumOfDigitsAsync(string inputStr) {
            return base.Channel.SumOfDigitsAsync(inputStr);
        }
        
        public string ReverseAString(string inputStr) {
            return base.Channel.ReverseAString(inputStr);
        }
        
        public System.Threading.Tasks.Task<string> ReverseAStringAsync(string inputStr) {
            return base.Channel.ReverseAStringAsync(inputStr);
        }
        
        public string PrintHtml(string inputStr1, string inputStr2) {
            return base.Channel.PrintHtml(inputStr1, inputStr2);
        }
        
        public System.Threading.Tasks.Task<string> PrintHtmlAsync(string inputStr1, string inputStr2) {
            return base.Channel.PrintHtmlAsync(inputStr1, inputStr2);
        }
        
        public string SortNumbers(int sortType, int[] inputArray) {
            return base.Channel.SortNumbers(sortType, inputArray);
        }
        
        public System.Threading.Tasks.Task<string> SortNumbersAsync(int sortType, int[] inputArray) {
            return base.Channel.SortNumbersAsync(sortType, inputArray);
        }
    }
}
